namespace RetailCare.Models.ServiceModel
{
    public class FeedabackModel
    {
        public int FEEDBACKID { get; set; }
        public string? TICKETID { get; set; }
        public int? TICKETCODE { get; set; }
        public string? FEEDBACKINFO { get; set; }
        public DateTime? WORKINGDATE { get; set; }
        public DateTime? PURCHASEDATE { get; set; }
        public int? PROBLEMID { get; set; }
        public int? ACTUALPROBLEMID { get; set; }
        public string? SUBPROBLEM { get; set; }
        public string? SOLVEDBY { get; set; }
        public int? ITEMID { get; set; }
        public int? PRODUCTID { get; set; }
        public int? PRMODELID { get; set; }
        public string? SERIALNO { get; set; }
        public int? PRODUCTQTY { get; set; }
        public string? USEDSPAREPARTS { get; set; }
        public string? REMARKS { get; set; }
        public string? BILLSTATUS { get; set; }
        public int? BILLID { get; set; }
        public int? CUSTOMERID { get; set; }
        public int? STATUSID { get; set; }
        public string? SRINFO { get; set; }
        public string? SRNUMBER { get; set; }
        public string? SRMODE { get; set; }
        public string? SRREJECTCAUSE { get; set; }
        public int? DILLERCODE { get; set; }
        public int? ISAPPROVED { get; set; }
        public string? APPROVEDBY { get; set; }
        public string? ENTRYBY { get; set; }
        public string? MODIFIEDBY { get; set; }
        public DateTime? ENTRYDATE { get; set; }
        public DateTime? MODIFIEDDATE { get; set; }
        public string? ENTRYPC { get; set; }
        public string? MODIFIEDPC { get; set; }
        public string? ASSISTID1 { get; set; }
        public string? ASSISTID2 { get; set; }
        public int? TECHID1 { get; set; }
        public int? TECHID2 { get; set; }
        public int? TECHID3 { get; set; }
        public int? CTYPEID { get; set; }
        public int? WACID { get; set; }
        public string? SRIMAGE1 { get; set; }
        public string? SRIMAGE2 { get; set; }
        public string? PSMODE { get; set; }
        public string? PSNOTE { get; set; }
        public int? SRDEPOID { get; set; }
        public int? PSDEPOID { get; set; }
        public string? SRAPPLYBY { get; set; }
        public DateTime? SRAPPLYDATE { get; set; }
        public string? SRAPPCHECK { get; set; }
        public DateTime? SRAPPCHECKDATE { get; set; }
        public string? SR1STAPV { get; set; }
        public DateTime? SR1STAPVDATE { get; set; }
        public string? SR2NDAPV { get; set; }
        public DateTime? SR2NDAPVDATE { get; set; }
        public string? SRFINALAPV { get; set; }
        public DateTime? SRFINALAPVDATE { get; set; }
        public DateTime? SRNOINDATE { get; set; }
        public string? PS1STAPV { get; set; }
        public string? PSFINALAPV { get; set; }
        public DateTime? PSAPPLYDATE { get; set; }
        public DateTime? PS1STAPPDATE { get; set; }
        public DateTime? PSDEPORECDATE { get; set; }
        public DateTime? PSSERVCRECDATE { get; set; }
        public DateTime? PSTRANTODEPODATE { get; set; }
        public DateTime? PSDELFRDEPO { get; set; }
        public string? PSREJCOZ { get; set; }
        public int? SENDCOST { get; set; }
        public string? FILE_PATH { get; set; }
        public int? PARTSCOST { get; set; }
        public int? OTHERSCOST { get; set; }
        public int? TOTALCOST { get; set; }
        public int? DISCOUNT { get; set; }
        public int? DISVALUE { get; set; }
        public int EXTENDEDCOST { get; set; }
        public string? DISCOUNTCOZ { get; set; }
        public string? DISREJCOZ { get; set; }
        public string? COSTSTATUS { get; set; }
        public string? DISAPVER { get; set; }
        public DateTime? DISAPVDATE { get; set; }
        public string? DMGINFO { get; set; }
        public string? DMMODE { get; set; }
        public string? DMREJCAUSE { get; set; }
        public int? DMDEPOID { get; set; }
        public string? DMAPPBY { get; set; }
        public DateTime? DMAPPDATE { get; set; }
        public string? DM1STAPV { get; set; }
        public DateTime? DM1STAPVDATE { get; set; }
        public string? DM2NDAPV { get; set; }
        public DateTime? DM2NDAPVDATE { get; set; }
        public string? DM3RDAPV { get; set; }
        public DateTime? DM3RDAPVDATE { get; set; }
        public string? DMFINALAPV { get; set; }
        public DateTime? DMFINALAPVDATE { get; set; }
        public string? CMSRINFO { get; set; }
        public string? CMSRMODE { get; set; }
        public string? CMSRREJCAUSE { get; set; }
        public string? CMSRVOLTAGE { get; set; }
        public int? CMSRCURRENT { get; set; }
        public int? SCRESISTANCE { get; set; }
        public int? MCRESISTANCE { get; set; }
        public string? CMSRBARPIC { get; set; }
        public string? PRODBARPIC { get; set; }
        public string? CMSRSERNO { get; set; }
        public string? CMSRAPPBY { get; set; }
        public DateTime? CMSRAPPDATE { get; set; }
        public string? CMSRFINALAPV { get; set; }
        public DateTime? CMSRFINALAPVDATE { get; set; }
        public string? CMSRSUPBRANDNAME { get; set; }
        public string? BARCODENO { get; set; }
        public string? CMSRFIRSTAPV { get; set; }
        public int? SUBMODELID { get; set; }
        public string? TRANSACTIONID { get; set; }
        public int? BILLAMOUNT { get; set; }
        public string? FILEPATH { get; set; }
        //public DateTime CmsrFirstApvDate { get; set; }
        //public string? CancelFirstApv { get; set; }
        //public DateTime CancelApvdate { get; set; }
        //public string? CancelFinalApv { get; set; }
        //public DateTime CancelFinalApvDatetime { get; set; }
        //public string? CancelReason { get; set; }

        // From Assign Table
        public string? CUSTOMERNAME { get; set; }
        public string? CUSTOMERCONTACTNO { get; set; }
        public string? CUSTOMERADDRESS { get; set; }
        public string? PRODUCTNAME { get; set; }
        public int? Productamount { get; set; } = 1;
    }
}
